package config

import (
	"book-service/domain"
	"log"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func SeedBooks(db *gorm.DB) {
	var count int64
	db.Model(&domain.Book{}).Count(&count)

	if count > 0 {
		log.Println("📚 Books table is not empty, skipping seeder")
		return
	}

	log.Println("🌱 Seeding books data...")

	books := []domain.Book{
		{
			ID:              uuid.New(),
			Title:           "As Long As The Lemon Trees Grow (Selama Pohon Lemon Tumbuh)",
			Author:          "Zoulfa Katouh",
			Publisher:       "Mizan Pustaka",
			Published:       time.Date(2023, 4, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/77e9d1b1-5d9f-4168-a87d-cad53bd473b1.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Historical", "Romance", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     10,
			AvailableCopies: 10,
			TotalPages:      479,
			Synopsis:        "Salama Kassab, seorang mahasiswi farmasi yang hidupnya hancur akibat perang saudara di Suriah, kini menjadi relawan medis di rumah sakit. Di tengah trauma dan bayangan masa lalunya yang terus menghantui dalam wujud halusinasi bernama Khawf, ia dihadapkan pada dilema berat: melarikan diri ke luar negeri bersama kakak iparnya yang sedang hamil demi keselamatan, atau tetap tinggal untuk membantu negaranya dan mengikuti panggilan hatinya yang perlahan tumbuh untuk Kenan, seorang pemuda yang tak ingin meninggalkan tanah airnya.",
		},
		{
			ID:              uuid.New(),
			Title:           "Teka-Teki Rumah Aneh (Henna Ie)",
			Author:          "Uketsu",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/ce97b903-674d-4e6e-a058-f3ab5901ac73.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller"},
			Language:        "Indonesian",
			TotalCopies:     5,
			AvailableCopies: 5,
			TotalPages:      224,
			Synopsis:        "Kisah bermula ketika seorang penulis lepas spesialis okultisme diminta untuk melihat denah sebuah rumah oleh kenalannya. Sekilas tidak ada yang aneh, namun ketika ia berkonsultasi dengan seorang arsitek bernama Kurihara, mereka menemukan kejanggalan demi kejanggalan: ruang tanpa jendela yang tersembunyi, pintu ganda, hingga kamar anak yang berada di lokasi tak wajar. Penyelidikan mereka perlahan menyingkap rahasia kelam dari keluarga pemilik rumah tersebut, membawa mereka pada dugaan mengerikan bahwa rumah itu mungkin dirancang untuk sebuah pembunuhan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sendiri",
			Author:          "Tere Liye",
			Publisher:       "Sabak Grip",
			Published:       time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/112cd552-e9e9-49b1-933e-b04e5fe53dcb.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Drama"},
			Language:        "Indonesian",
			TotalCopies:     7,
			AvailableCopies: 7,
			TotalPages:      320,
			Synopsis:        "Melalui gaya bahasa yang khas dan reflektif, Tere Liye mengajak pembaca untuk menyelami makna kesendirian di tengah hiruk-pikuk dunia modern. Buku ini mengupas bagaimana perasaan sepi sering kali menjadi ruang terbaik bagi seseorang untuk merenung, mengenali diri sendiri lebih dalam, dan berdamai dengan luka masa lalu. Dengan berbagai kisah inspiratif yang menyentuh hati, pembaca diajak untuk memahami bahwa menyendiri bukanlah sebuah kelemahan, melainkan sebuah jeda berharga untuk merangkai kembali kekuatan hidup.",
		},
		{
			ID:              uuid.New(),
			Title:           "Pulang",
			Author:          "Tere Liye",
			Publisher:       "Republika Penerbit",
			Published:       time.Date(2015, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/d0fdedee-f54a-481b-a48c-c3061567c794.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Adventure", "Thriller"},
			Language:        "Indonesian",
			TotalCopies:     12,
			AvailableCopies: 12,
			TotalPages:      400,
			Synopsis:        "Bujang, seorang pemuda dari pelosok Sumatra, dibawa ke ibu kota oleh Tauke Besar untuk dididik menjadi tukang pukul nomor satu di Keluarga Tong, sebuah klan shadow economy penguasa pasar gelap. Seiring berjalannya waktu, Bujang tidak hanya dilatih secara fisik namun juga disekolahkan ke luar negeri, menjadikannya mesin penyelesai masalah yang cerdas dan tak kenal takut. Namun, di puncak kejayaannya, ia dikhianati dan harus melakukan perjalanan panjang yang memaksanya menghadapi masa lalu, berdamai dengan kenangan orang tuanya, dan mencari makna sejati dari kata 'pulang'.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sebuah Seni untuk Bersikap Bodo Amat",
			Author:          "Mark Manson",
			Publisher:       "Grasindo",
			Published:       time.Date(2018, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/9a0fbb67-38b1-4e63-8901-75fcb604ed58.jpg",
			Category:        []string{"Self-Help"},
			Genre:           nil, // Bukan novel, tidak punya genre
			Language:        "Indonesian",
			TotalCopies:     8,
			AvailableCopies: 8,
			TotalPages:      246,
			Synopsis:        "Sebagai reaksi terhadap budaya modern yang selalu menuntut pandangan positif palsu, Mark Manson memberikan pendekatan yang lebih jujur dan waras dalam menjalani hidup. Lewat buku ini, ia berargumen bahwa penderitaan dan kegagalan adalah bagian tak terpisahkan dari eksistensi manusia yang justru memberikan makna. Daripada berusaha mempedulikan segala hal, kita diajarkan untuk mengenali batasan diri, menerima kekurangan, dan memilih dengan bijak hal-hal apa saja yang benar-benar pantas untuk kita pedulikan agar hidup menjadi lebih autentik dan bahagia.",
		},
		{
			ID:              uuid.New(),
			Title:           "Laut Bercerita",
			Author:          "Leila S. Chudori",
			Publisher:       "Kepustakaan Populer Gramedia",
			Published:       time.Date(2017, 10, 23, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/dc9365f8-ed28-41c1-b71c-1193e1b6366f.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Historical", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     15,
			AvailableCopies: 15,
			TotalPages:      379,
			Synopsis:        "Buku ini menarasikan dua sudut pandang berbeda yang terpisah oleh waktu. Bagian pertama menceritakan Biru Laut, seorang mahasiswa sekaligus aktivis yang berjuang menuntut reformasi pada masa Orde Baru, namun harus berakhir diculik dan disiksa bersama kawan-kawannya. Bagian kedua diambil dari kacamata Asmara Jati, adik Laut, yang mewakili keluarga korban dalam pencarian panjang menuntut keadilan. Novel ini merupakan sebuah eksplorasi mendalam tentang persahabatan, pengkhianatan, hilangnya nyawa, dan duka tak berujung dari mereka yang ditinggalkan oleh para aktivis 1998.",
		},
		{
			ID:              uuid.New(),
			Title:           "Salvation of a Saint (Dosa Malaikat)",
			Author:          "Keigo Higashino",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2021, 3, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/89796088-9da4-4206-b48e-5bdd3ae24e4e.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller", "Detective"},
			Language:        "Indonesian",
			TotalCopies:     4,
			AvailableCopies: 4,
			TotalPages:      347,
			Synopsis:        "Yoshitaka Mashiba ditemukan tewas akibat kopi beracun tak lama setelah ia mengutarakan niatnya untuk menceraikan istrinya, Ayane. Sebagai istri yang disakiti, Ayane otomatis menjadi tersangka utama Detektif Kusanagi. Namun, Ayane memiliki alibi yang tak terbantahkan karena saat kejadian, ia sedang berada di Hokkaido, ratusan kilometer jauhnya. Profesor Yukawa alias Detektif Galileo pun turun tangan untuk membongkar teka-teki pembunuhan ini, yang ia sebut memiliki trik nyaris mustahil dan hanya bisa dilakukan oleh seseorang dengan dedikasi serta keputusasaan yang luar biasa.",
		},
		{
			ID:              uuid.New(),
			Title:           "Malice (Catatan Pembunuhan Sang Novelis)",
			Author:          "Keigo Higashino",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2020, 8, 10, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/3930565b-df67-4518-a2c9-b02be88305d8.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Detective"},
			Language:        "Indonesian",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      304,
			Synopsis:        "Kunihiko Hidaka, seorang novelis sukses, ditemukan tewas di rumahnya tepat pada malam sebelum ia berencana pindah ke Kanada. Penemunya adalah istri Hidaka sendiri dan sahabat masa kecilnya, Osamu Nonoguchi, yang juga seorang penulis buku anak. Detektif Kyoichiro Kaga yang memimpin penyelidikan dengan cepat berhasil menemukan sang pembunuh. Namun, pengakuan sang pembunuh justru membuka kotak pandora yang lebih gelap. Novel ini berfokus pada misteri 'mengapa' pembunuhan itu terjadi, mengupas lapisan demi lapisan kebencian, kecemburuan, dan sisi paling kelam dari sifat manusia.",
		},
		{
			ID:              uuid.New(),
			Title:           "Keajaiban Toko Kelontong Namiya",
			Author:          "Keigo Higashino",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/3bde4e79-dadd-462f-b6df-bd2c58201072.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Fantasy", "Drama", "Magical Realism"},
			Language:        "Indonesian",
			TotalCopies:     9,
			AvailableCopies: 9,
			TotalPages:      400,
			Synopsis:        "Tiga pemuda berandalan yang sedang dalam pelarian bersembunyi di sebuah toko kelontong tua yang sudah lama ditinggalkan. Di tengah malam, tiba-tiba sepucuk surat misterius diselipkan melalui celah pintu bergulir, berisi permintaan nasihat dari seseorang di masa lalu. Berawal dari keisengan membalas surat tersebut, mereka mendapati diri mereka terhubung dengan berbagai orang dari dekade yang berbeda. Seiring berjalannya malam, keajaiban toko Namiya perlahan merajut takdir ketiga pemuda tersebut dengan orang-orang yang mereka bantu, menuntun mereka pada sebuah pencerahan hidup.",
		},
		{
			ID:              uuid.New(),
			Title:           "Perahu Kertas",
			Author:          "Dee Lestari",
			Publisher:       "Bentang Pustaka",
			Published:       time.Date(2009, 8, 29, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/d9a06f50-5d5e-4081-8df7-c069fe58506a.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Romance", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     11,
			AvailableCopies: 11,
			TotalPages:      444,
			Synopsis:        "Kugy, seorang gadis unik yang bercita-cita menjadi penulis dongeng dan kerap mengirim surat untuk Neptunus, bertemu dengan Keenan, seorang pemuda cerdas yang dipaksa ayahnya belajar bisnis padahal ia memiliki bakat luar biasa dalam melukis. Pertemuan mereka menumbuhkan ikatan batin yang tak terpisahkan, di mana dongeng Kugy menjadi inspirasi lukisan Keenan. Sayangnya, waktu dan keadaan selalu tidak berpihak, menarik mereka menjauh hingga terjebak dalam hubungan dengan orang lain. Novel ini adalah perjalanan tentang menemukan jati diri, impian, dan takdir cinta yang menyerupai radar di hati mereka.",
		},
		{
			ID:              uuid.New(),
			Title:           "Putri Kedua (Second Sister)",
			Author:          "Chan Ho-Kei",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2021, 2, 21, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/b40ab504-72f8-4913-b0d0-6014f26f1ae4.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller", "Detective"},
			Language:        "Indonesian",
			TotalCopies:     5,
			AvailableCopies: 5,
			TotalPages:      632,
			Synopsis:        "Nga-Yee, seorang pustakawan yang pendiam, hancur hatinya ketika adik perempuan satu-satunya yang baru berusia lima belas tahun, Siu-Man, tewas bunuh diri dengan melompat dari apartemen mereka. Menolak percaya bahwa adiknya bertindak tanpa alasan, Nga-Yee menyelidiki kematian tersebut dan menemukan bahwa adiknya menjadi korban perundungan siber yang parah. Ia kemudian menyewa jasa N, seorang peretas jenius yang eksentrik dan manipulatif, untuk melacak identitas anonim para perundung. Berdua, mereka menyelami sisi gelap dunia maya untuk membalas dendam dengan cara yang tak terbayangkan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Seporsi Mie Ayam Sebelum Mati",
			Author:          "Brian Khrisna",
			Publisher:       "Grasindo",
			Published:       time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.5,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/f21b3754-9e8b-441e-af2c-35f83e746f3a.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Drama", "Romance"},
			Language:        "Indonesian",
			TotalCopies:     4,
			AvailableCopies: 4,
			TotalPages:      216,
			Synopsis:        "Novel ini menghadirkan sebuah drama emosional yang lekat dengan realitas kehidupan sehari-hari, berpusat pada kenangan, penyesalan, dan momen-momen yang sering kali kita anggap remeh. Melalui simbolisme seporsi mie ayam yang dinikmati sebelum kematian tiba, Brian Khrisna menyajikan narasi menyentuh tentang bagaimana manusia menghadapi pahit manisnya takdir. Kisah ini mengajak pembaca untuk merefleksikan hubungan yang belum terselesaikan dan merangkul kedamaian sebelum waktu benar-benar habis di batas kehidupan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sisi Tergelap Surga",
			Author:          "Brian Khrisna",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/222331df-7c6a-44bb-bf76-31de58e713d0.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Drama"},
			Language:        "Indonesian",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      304,
			Synopsis:        "Mengambil latar di sudut-sudut kelam kota Jakarta yang seolah menjadi ironi bagi mereka yang menyebutnya 'surga', novel ini membongkar realitas kehidupan kaum marjinal dan masyarakat kelas pekerja bawah. Melalui karakter-karakternya yang hidup dengan latar belakang keluarga hancur dan impian yang kandas, Brian Khrisna menyuguhkan potret jujur tentang kemiskinan, kemunafikan sosial, serta perjuangan manusia untuk tetap waras. Buku ini adalah tamparan keras sekaligus pelukan hangat bagi siapa saja yang terus berjuang di tengah kejamnya ibu kota.",
		},
		{
			ID:              uuid.New(),
			Title:           "Bandung After Rain",
			Author:          "Wulan Nur Amalia",
			Publisher:       "Black Swan Books",
			Published:       time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/2c9560f2-13c7-4dc8-a3ed-bff4b91e8509.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Romance", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     3,
			AvailableCopies: 3,
			TotalPages:      282,
			Synopsis:        "Hema dan Rania adalah dua jiwa yang dipertemukan dan diikat oleh kenangan-kenangan di bawah rintik hujan kota Bandung. Seiring dengan cuaca kota yang syahdu dan romantis, hubungan mereka diwarnai oleh konflik emosional, luka masa lalu, dan keraguan untuk melangkah maju. Novel ini menelusuri bagaimana mereka mencoba menyembuhkan satu sama lain, berhadapan dengan ekspektasi, serta mempertanyakan apakah cinta yang mereka bangun mampu bertahan melawan badai yang terus menguji kedewasaan mereka.",
		},
		{
			ID:              uuid.New(),
			Title:           "Teka-Teki Gambar Aneh",
			Author:          "Uketsu",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2026, 2, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/dd6e1bd3-783c-4bf5-8950-1ca7f9df6cfe.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller"},
			Language:        "Indonesian",
			TotalCopies:     8,
			AvailableCopies: 8,
			TotalPages:      312,
			Synopsis:        "Sebagai penerus dari fenomena Teka-Teki Rumah Aneh, Uketsu kembali hadir dengan misteri yang berpusat pada sembilan buah sketsa gambar yang sekilas tampak damai dan polos. Namun, ketika protagonis novel ini mulai menelisik dan menghubungkan detail-detail kecil dari gambar tersebut, kengerian demi kengerian mulai bermunculan. Sketsa-sketsa itu ternyata menyembunyikan jejak-jejak pembunuhan, rahasia keluarga yang busuk, dan kutukan masa lalu yang saling berkaitan. Pembaca akan diajak bermain teka-teki secara interaktif untuk merangkai sebuah kebenaran yang membuat bulu kuduk berdiri.",
		},
		{
			ID:              uuid.New(),
			Title:           "The Innovators",
			Author:          "Walter Isaacson",
			Publisher:       "Simon & Schuster",
			Published:       time.Date(2014, 10, 7, 0, 0, 0, 0, time.UTC),
			Ratings:         4.5,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/88fdc4d4-1351-4285-b18e-2c7d6c7cc29e.jpg",
			Category:        []string{"Technology", "History"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     5,
			AvailableCopies: 5,
			TotalPages:      560,
			Synopsis:        "Buku ini menceritakan sejarah para pelopor, peretas, jenius, dan geek yang menciptakan revolusi digital. Dari Ada Lovelace di abad ke-19 hingga tokoh-tokoh besar seperti Alan Turing, John von Neumann, Robert Noyce, Bill Gates, Steve Wozniak, Steve Jobs, Tim Berners-Lee, dan Larry Page, Isaacson mengungkap kisah kolaborasi luar biasa di balik lahirnya komputer dan internet.",
		},
		{
			ID:              uuid.New(),
			Title:           "Steve Jobs",
			Author:          "Walter Isaacson",
			Publisher:       "Simon & Schuster",
			Published:       time.Date(2011, 10, 24, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/d5cb0948-e0bb-476b-a703-ddda857c3e1f.jpg",
			Category:        []string{"Technology", "Biography"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     10,
			AvailableCopies: 10,
			TotalPages:      656,
			Synopsis:        "Berdasarkan lebih dari empat puluh wawancara dengan Steve Jobs, serta ratusan wawancara dengan anggota keluarga, teman, musuh, pesaing, dan koleganya, buku ini memaparkan kehidupan rollercoaster dan kepribadian intens seorang pengusaha kreatif yang dorongannya untuk kesempurnaan merevolusi enam industri: komputer pribadi, film animasi, musik, ponsel, komputasi tablet, dan penerbitan digital.",
		},
		{
			ID:              uuid.New(),
			Title:           "The Pragmatic Programmer",
			Author:          "Andrew Hunt, David Thomas",
			Publisher:       "Addison-Wesley",
			Published:       time.Date(1999, 10, 20, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/97b02a56-046f-4227-8a98-4d343ef55d5c.jpg",
			Category:        []string{"Technology", "Programming"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     7,
			AvailableCopies: 7,
			TotalPages:      352,
			Synopsis:        "Buku ini memotong spesifikasi dan menyoroti esensi pengembangan perangkat lunak terlepas dari bahasa pengkodean yang digunakan. Ini mengeksplorasi berbagai topik mulai dari tanggung jawab pribadi dan pengembangan karier hingga teknik arsitektur untuk menjaga kode tetap fleksibel dan mudah diadaptasi dan digunakan kembali.",
		},
		{
			ID:              uuid.New(),
			Title:           "Clean Code",
			Author:          "Robert C. Martin",
			Publisher:       "Prentice Hall",
			Published:       time.Date(2008, 8, 11, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/82b20ea7-7c9c-4512-bda4-c541f67039b6.jpg",
			Category:        []string{"Technology", "Programming"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      464,
			Synopsis:        "Clean Code dibagi menjadi tiga bagian. Yang pertama menjelaskan prinsip-prinsip, pola, dan praktik menulis kode bersih. Bagian kedua berisi beberapa studi kasus pembersihan kode. Bagian ketiga adalah daftar heuristik dan 'bau' yang dikumpulkan saat membuat studi kasus, membentuk basis pengetahuan yang kuat tentang bagaimana kita berpikir saat menulis, membaca, dan membersihkan kode.",
		},
		{
			ID:              uuid.New(),
			Title:           "Zero to One",
			Author:          "Peter Thiel, Blake Masters",
			Publisher:       "Crown Business",
			Published:       time.Date(2014, 9, 16, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/f3c46d20-c7c5-4626-b2f1-b5b88a9c8727.jpg",
			Category:        []string{"Technology", "Business"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     12,
			AvailableCopies: 12,
			TotalPages:      224,
			Synopsis:        "Buku ini menyajikan cara pandang baru yang optimis mengenai masa depan kemajuan di Amerika dan pandangan orisinal tentang cara menciptakan nilai di dunia. Thiel menjelaskan bahwa kemajuan bisa dicapai dalam berbagai bentuk, tetapi inovasi sejati berasal dari melakukan sesuatu yang sama sekali baru, yaitu beranjak dari 0 ke 1.",
		},
		{
			ID:              uuid.New(),
			Title:           "Thinking, Fast and Slow",
			Author:          "Daniel Kahneman",
			Publisher:       "Farrar, Straus and Giroux",
			Published:       time.Date(2011, 10, 25, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/798e106f-9dfe-4acb-bd4a-d7006b155261.jpg",
			Category:        []string{"Business", "Self-Help"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     8,
			AvailableCopies: 8,
			TotalPages:      499,
			Synopsis:        "Kahneman membawa kita pada tur mendalam tentang pikiran manusia, menjelaskan dua sistem yang mendorong cara kita berpikir: Sistem 1 yang cepat, intuitif, dan emosional; serta Sistem 2 yang lebih lambat, deliberatif, dan logis. Buku ini mengungkap kelemahan serta keunggulan pemikiran cepat, serta pengaruh bias kognitif dalam pengambilan keputusan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Good to Great",
			Author:          "Jim Collins",
			Publisher:       "HarperBusiness",
			Published:       time.Date(2001, 10, 16, 0, 0, 0, 0, time.UTC),
			Ratings:         4.5,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/54e0b9c0-2c37-4441-a6de-ebd7fd9a8609.jpg",
			Category:        []string{"Business"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     9,
			AvailableCopies: 9,
			TotalPages:      320,
			Synopsis:        "Mengapa beberapa perusahaan mampu melakukan lompatan menjadi perusahaan luar biasa, sementara yang lain tidak? Jim Collins bersama tim penelitinya mempelajari berbagai perusahaan selama lima tahun untuk menemukan prinsip-prinsip universal yang mendasari transisi dari baik menjadi hebat, menantang banyak anggapan tradisional tentang manajemen bisnis.",
		},
		{
			ID:              uuid.New(),
			Title:           "The Lean Startup",
			Author:          "Eric Ries",
			Publisher:       "Crown Business",
			Published:       time.Date(2011, 9, 13, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/d282acc3-2011-4c87-beca-456e10a732e2.jpg",
			Category:        []string{"Business", "Technology"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     11,
			AvailableCopies: 11,
			TotalPages:      336,
			Synopsis:        "The Lean Startup memberikan pendekatan ilmiah untuk menciptakan dan mengelola perusahaan rintisan agar produk yang dibuat sampai ke tangan pelanggan lebih cepat. Menggunakan prinsip-prinsip lean manufacturing, buku ini menekankan pembelajaran tervalidasi, eksperimen iteratif, dan pengukuran progres aktual untuk membangun bisnis yang sukses.",
		},
		{
			ID:              uuid.New(),
			Title:           "Rich Dad Poor Dad",
			Author:          "Robert T. Kiyosaki",
			Publisher:       "Plata Publishing",
			Published:       time.Date(1997, 4, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/685d5543-998f-4325-a2a6-72cd14341838.jpg",
			Category:        []string{"Business", "Self-Help"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     15,
			AvailableCopies: 15,
			TotalPages:      336,
			Synopsis:        "Kisah Robert Kiyosaki tentang tumbuh dewasa dengan dua orang ayah — ayah kandungnya dan ayah sahabatnya — serta cara pria-pria ini membentuk pemikirannya mengenai investasi dan kekayaan. Buku ini menantang mitos bahwa Anda harus memiliki penghasilan tinggi untuk menjadi kaya dan menjelaskan perbedaan mendasar antara bekerja untuk uang dan membuat uang bekerja untuk Anda.",
		},
		{
			ID:              uuid.New(),
			Title:           "Shoe Dog",
			Author:          "Phil Knight",
			Publisher:       "Simon & Schuster",
			Published:       time.Date(2016, 4, 26, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/42795b66-bbea-4462-9daf-0fcf81da10e9.jpg",
			Category:        []string{"Business", "Biography"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      400,
			Synopsis:        "Dalam memoar yang memukau ini, pendiri dan mantan CEO Nike, Phil Knight, menceritakan kisah perjalanan perusahaannya sejak berdiri dengan investasi minim hingga menjadi salah satu merek paling ikonik, inovatif, dan menguntungkan di dunia. Sebuah cerita tentang semangat kewirausahaan, risiko, keraguan, kegagalan, dan kemenangan besar.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sapiens: A Brief History of Humankind",
			Author:          "Yuval Noah Harari",
			Publisher:       "Harper",
			Published:       time.Date(2011, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/77289d23-a32f-4a00-b4a4-aacdbdccfd26.png",
			Category:        []string{"History"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     14,
			AvailableCopies: 14,
			TotalPages:      443,
			Synopsis:        "Dalam Sapiens, Dr. Yuval Noah Harari menelusuri sejarah luar biasa spesies manusia, mulai dari primata tak berarti yang hidup di Afrika prasejarah, hingga menguasai bumi melalui tiga revolusi besar: Kognitif, Agrikultur, dan Saintifik. Buku ini menggabungkan wawasan biologi, antropologi, dan sejarah untuk memahami bagaimana kita bisa menjadi manusia modern.",
		},
		{
			ID:              uuid.New(),
			Title:           "Guns, Germs, and Steel",
			Author:          "Jared Diamond",
			Publisher:       "W. W. Norton & Company",
			Published:       time.Date(1997, 3, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.5,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/6243f009-5988-4271-8082-af267420298c.jpg",
			Category:        []string{"History"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     7,
			AvailableCopies: 7,
			TotalPages:      480,
			Synopsis:        "Sebuah tinjauan interdisipliner mengenai mengapa peradaban Eurasia menaklukkan benua-benua lain di dunia. Diamond berargumen bahwa dominasi peradaban Eurasia berakar pada perbedaan geografis dan lingkungan benua Eurasia dibandingkan daratan lain, bukan karena perbedaan biologis atau kecerdasan yang inheren pada manusianya.",
		},
		{
			ID:              uuid.New(),
			Title:           "The Silk Roads",
			Author:          "Peter Frankopan",
			Publisher:       "Bloomsbury Publishing",
			Published:       time.Date(2015, 8, 27, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/5eeabf2b-1b7a-405e-98a6-3c34b8f435f7.jpg",
			Category:        []string{"History"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     5,
			AvailableCopies: 5,
			TotalPages:      656,
			Synopsis:        "Sejarah dunia yang revolusioner dari perspektif baru, fokus pada Timur. Peter Frankopan memindahkan pusat gravitasi sejarah global dari Eropa kembali ke Timur Tengah dan Asia, menyusuri kembali ribuan tahun kekaisaran, perdagangan, budaya, dan konflik di rute perdagangan Jalur Sutra yang legendaris.",
		},
		{
			ID:              uuid.New(),
			Title:           "A Little History of the World",
			Author:          "E.H. Gombrich",
			Publisher:       "Yale University Press",
			Published:       time.Date(1935, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/bc48e4ee-7ce7-47b4-8bbc-cf4b161e1381.jpg",
			Category:        []string{"History"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     4,
			AvailableCopies: 4,
			TotalPages:      284,
			Synopsis:        "Ditulis pada tahun 1935, buku ini merupakan salah satu narasi sejarah paling menawan dan populer yang pernah ada. E.H. Gombrich menceritakan kisah umat manusia, dari Zaman Batu hingga era nuklir, dalam 40 bab singkat yang lugas, menjadikannya pengantar sejarah dunia yang sangat sempurna bagi segala usia.",
		},
		{
			ID:              uuid.New(),
			Title:           "SPQR: A History of Ancient Rome",
			Author:          "Mary Beard",
			Publisher:       "Liveright",
			Published:       time.Date(2015, 10, 20, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/0b927f88-514a-4204-9ba8-365c1b0d1f46.jpg",
			Category:        []string{"History"},
			Genre:           nil,
			Language:        "English",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      608,
			Synopsis:        "Karya magistral Mary Beard tentang sejarah Romawi kuno menantang banyak mitos yang selama ini diyakini masyarakat. Beard mengungkap bagaimana Roma, dari desa kumuh di Italia tengah, mampu menguasai wilayah luas dan menjadi kekaisaran pertama. Buku ini memberikan pandangan baru terhadap figur ikonik seperti Hannibal, Caesar, dan Augustus.",
		},
	}

	if err := db.Create(&books).Error; err != nil {
		log.Fatalf("Failed to seed books: %v", err)
	}

	log.Println("✅ Books seeded successfully")
}
