package config

import (
	"book-service/domain"
	"log"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

func SeedBooks(db *gorm.DB) {
	var count int64
	db.Model(&domain.Book{}).Count(&count)

	if count > 0 {
		log.Println("📚 Books table is not empty, skipping seeder")
		return
	}

	log.Println("🌱 Seeding books data...")

	books := []domain.Book{
		{
			ID:              uuid.New(),
			Title:           "As Long As The Lemon Trees Grow (Selama Pohon Lemon Tumbuh)",
			Author:          "Zoulfa Katouh",
			Publisher:       "Mizan Pustaka",
			Published:       time.Date(2023, 4, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/77e9d1b1-5d9f-4168-a87d-cad53bd473b1.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Historical", "Romance", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     10,
			AvailableCopies: 10,
			TotalPages:      479,
			Synopsis:        "Salama Kassab, seorang mahasiswi farmasi yang hidupnya hancur akibat perang saudara di Suriah, kini menjadi relawan medis di rumah sakit. Di tengah trauma dan bayangan masa lalunya yang terus menghantui dalam wujud halusinasi bernama Khawf, ia dihadapkan pada dilema berat: melarikan diri ke luar negeri bersama kakak iparnya yang sedang hamil demi keselamatan, atau tetap tinggal untuk membantu negaranya dan mengikuti panggilan hatinya yang perlahan tumbuh untuk Kenan, seorang pemuda yang tak ingin meninggalkan tanah airnya.",
		},
		{
			ID:              uuid.New(),
			Title:           "Teka-Teki Rumah Aneh (Henna Ie)",
			Author:          "Uketsu",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/ce97b903-674d-4e6e-a058-f3ab5901ac73.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller"},
			Language:        "Indonesian",
			TotalCopies:     5,
			AvailableCopies: 5,
			TotalPages:      224,
			Synopsis:        "Kisah bermula ketika seorang penulis lepas spesialis okultisme diminta untuk melihat denah sebuah rumah oleh kenalannya. Sekilas tidak ada yang aneh, namun ketika ia berkonsultasi dengan seorang arsitek bernama Kurihara, mereka menemukan kejanggalan demi kejanggalan: ruang tanpa jendela yang tersembunyi, pintu ganda, hingga kamar anak yang berada di lokasi tak wajar. Penyelidikan mereka perlahan menyingkap rahasia kelam dari keluarga pemilik rumah tersebut, membawa mereka pada dugaan mengerikan bahwa rumah itu mungkin dirancang untuk sebuah pembunuhan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sendiri",
			Author:          "Tere Liye",
			Publisher:       "Sabak Grip",
			Published:       time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/112cd552-e9e9-49b1-933e-b04e5fe53dcb.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Drama"},
			Language:        "Indonesian",
			TotalCopies:     7,
			AvailableCopies: 7,
			TotalPages:      320,
			Synopsis:        "Melalui gaya bahasa yang khas dan reflektif, Tere Liye mengajak pembaca untuk menyelami makna kesendirian di tengah hiruk-pikuk dunia modern. Buku ini mengupas bagaimana perasaan sepi sering kali menjadi ruang terbaik bagi seseorang untuk merenung, mengenali diri sendiri lebih dalam, dan berdamai dengan luka masa lalu. Dengan berbagai kisah inspiratif yang menyentuh hati, pembaca diajak untuk memahami bahwa menyendiri bukanlah sebuah kelemahan, melainkan sebuah jeda berharga untuk merangkai kembali kekuatan hidup.",
		},
		{
			ID:              uuid.New(),
			Title:           "Pulang",
			Author:          "Tere Liye",
			Publisher:       "Republika Penerbit",
			Published:       time.Date(2015, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/d0fdedee-f54a-481b-a48c-c3061567c794.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Adventure", "Thriller"},
			Language:        "Indonesian",
			TotalCopies:     12,
			AvailableCopies: 12,
			TotalPages:      400,
			Synopsis:        "Bujang, seorang pemuda dari pelosok Sumatra, dibawa ke ibu kota oleh Tauke Besar untuk dididik menjadi tukang pukul nomor satu di Keluarga Tong, sebuah klan shadow economy penguasa pasar gelap. Seiring berjalannya waktu, Bujang tidak hanya dilatih secara fisik namun juga disekolahkan ke luar negeri, menjadikannya mesin penyelesai masalah yang cerdas dan tak kenal takut. Namun, di puncak kejayaannya, ia dikhianati dan harus melakukan perjalanan panjang yang memaksanya menghadapi masa lalu, berdamai dengan kenangan orang tuanya, dan mencari makna sejati dari kata 'pulang'.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sebuah Seni untuk Bersikap Bodo Amat",
			Author:          "Mark Manson",
			Publisher:       "Grasindo",
			Published:       time.Date(2018, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/9a0fbb67-38b1-4e63-8901-75fcb604ed58.jpg",
			Category:        []string{"Self-Help"},
			Genre:           nil, // Bukan novel, tidak punya genre
			Language:        "Indonesian",
			TotalCopies:     8,
			AvailableCopies: 8,
			TotalPages:      246,
			Synopsis:        "Sebagai reaksi terhadap budaya modern yang selalu menuntut pandangan positif palsu, Mark Manson memberikan pendekatan yang lebih jujur dan waras dalam menjalani hidup. Lewat buku ini, ia berargumen bahwa penderitaan dan kegagalan adalah bagian tak terpisahkan dari eksistensi manusia yang justru memberikan makna. Daripada berusaha mempedulikan segala hal, kita diajarkan untuk mengenali batasan diri, menerima kekurangan, dan memilih dengan bijak hal-hal apa saja yang benar-benar pantas untuk kita pedulikan agar hidup menjadi lebih autentik dan bahagia.",
		},
		{
			ID:              uuid.New(),
			Title:           "Laut Bercerita",
			Author:          "Leila S. Chudori",
			Publisher:       "Kepustakaan Populer Gramedia",
			Published:       time.Date(2017, 10, 23, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/dc9365f8-ed28-41c1-b71c-1193e1b6366f.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Historical", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     15,
			AvailableCopies: 15,
			TotalPages:      379,
			Synopsis:        "Buku ini menarasikan dua sudut pandang berbeda yang terpisah oleh waktu. Bagian pertama menceritakan Biru Laut, seorang mahasiswa sekaligus aktivis yang berjuang menuntut reformasi pada masa Orde Baru, namun harus berakhir diculik dan disiksa bersama kawan-kawannya. Bagian kedua diambil dari kacamata Asmara Jati, adik Laut, yang mewakili keluarga korban dalam pencarian panjang menuntut keadilan. Novel ini merupakan sebuah eksplorasi mendalam tentang persahabatan, pengkhianatan, hilangnya nyawa, dan duka tak berujung dari mereka yang ditinggalkan oleh para aktivis 1998.",
		},
		{
			ID:              uuid.New(),
			Title:           "Salvation of a Saint (Dosa Malaikat)",
			Author:          "Keigo Higashino",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2021, 3, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/89796088-9da4-4206-b48e-5bdd3ae24e4e.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller", "Detective"},
			Language:        "Indonesian",
			TotalCopies:     4,
			AvailableCopies: 4,
			TotalPages:      347,
			Synopsis:        "Yoshitaka Mashiba ditemukan tewas akibat kopi beracun tak lama setelah ia mengutarakan niatnya untuk menceraikan istrinya, Ayane. Sebagai istri yang disakiti, Ayane otomatis menjadi tersangka utama Detektif Kusanagi. Namun, Ayane memiliki alibi yang tak terbantahkan karena saat kejadian, ia sedang berada di Hokkaido, ratusan kilometer jauhnya. Profesor Yukawa alias Detektif Galileo pun turun tangan untuk membongkar teka-teki pembunuhan ini, yang ia sebut memiliki trik nyaris mustahil dan hanya bisa dilakukan oleh seseorang dengan dedikasi serta keputusasaan yang luar biasa.",
		},
		{
			ID:              uuid.New(),
			Title:           "Malice (Catatan Pembunuhan Sang Novelis)",
			Author:          "Keigo Higashino",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2020, 8, 10, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/3930565b-df67-4518-a2c9-b02be88305d8.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Detective"},
			Language:        "Indonesian",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      304,
			Synopsis:        "Kunihiko Hidaka, seorang novelis sukses, ditemukan tewas di rumahnya tepat pada malam sebelum ia berencana pindah ke Kanada. Penemunya adalah istri Hidaka sendiri dan sahabat masa kecilnya, Osamu Nonoguchi, yang juga seorang penulis buku anak. Detektif Kyoichiro Kaga yang memimpin penyelidikan dengan cepat berhasil menemukan sang pembunuh. Namun, pengakuan sang pembunuh justru membuka kotak pandora yang lebih gelap. Novel ini berfokus pada misteri 'mengapa' pembunuhan itu terjadi, mengupas lapisan demi lapisan kebencian, kecemburuan, dan sisi paling kelam dari sifat manusia.",
		},
		{
			ID:              uuid.New(),
			Title:           "Keajaiban Toko Kelontong Namiya",
			Author:          "Keigo Higashino",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.9,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/3bde4e79-dadd-462f-b6df-bd2c58201072.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Fantasy", "Drama", "Magical Realism"},
			Language:        "Indonesian",
			TotalCopies:     9,
			AvailableCopies: 9,
			TotalPages:      400,
			Synopsis:        "Tiga pemuda berandalan yang sedang dalam pelarian bersembunyi di sebuah toko kelontong tua yang sudah lama ditinggalkan. Di tengah malam, tiba-tiba sepucuk surat misterius diselipkan melalui celah pintu bergulir, berisi permintaan nasihat dari seseorang di masa lalu. Berawal dari keisengan membalas surat tersebut, mereka mendapati diri mereka terhubung dengan berbagai orang dari dekade yang berbeda. Seiring berjalannya malam, keajaiban toko Namiya perlahan merajut takdir ketiga pemuda tersebut dengan orang-orang yang mereka bantu, menuntun mereka pada sebuah pencerahan hidup.",
		},
		{
			ID:              uuid.New(),
			Title:           "Perahu Kertas",
			Author:          "Dee Lestari",
			Publisher:       "Bentang Pustaka",
			Published:       time.Date(2009, 8, 29, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/d9a06f50-5d5e-4081-8df7-c069fe58506a.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Romance", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     11,
			AvailableCopies: 11,
			TotalPages:      444,
			Synopsis:        "Kugy, seorang gadis unik yang bercita-cita menjadi penulis dongeng dan kerap mengirim surat untuk Neptunus, bertemu dengan Keenan, seorang pemuda cerdas yang dipaksa ayahnya belajar bisnis padahal ia memiliki bakat luar biasa dalam melukis. Pertemuan mereka menumbuhkan ikatan batin yang tak terpisahkan, di mana dongeng Kugy menjadi inspirasi lukisan Keenan. Sayangnya, waktu dan keadaan selalu tidak berpihak, menarik mereka menjauh hingga terjebak dalam hubungan dengan orang lain. Novel ini adalah perjalanan tentang menemukan jati diri, impian, dan takdir cinta yang menyerupai radar di hati mereka.",
		},
		{
			ID:              uuid.New(),
			Title:           "Putri Kedua (Second Sister)",
			Author:          "Chan Ho-Kei",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2021, 2, 21, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/b40ab504-72f8-4913-b0d0-6014f26f1ae4.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller", "Detective"},
			Language:        "Indonesian",
			TotalCopies:     5,
			AvailableCopies: 5,
			TotalPages:      632,
			Synopsis:        "Nga-Yee, seorang pustakawan yang pendiam, hancur hatinya ketika adik perempuan satu-satunya yang baru berusia lima belas tahun, Siu-Man, tewas bunuh diri dengan melompat dari apartemen mereka. Menolak percaya bahwa adiknya bertindak tanpa alasan, Nga-Yee menyelidiki kematian tersebut dan menemukan bahwa adiknya menjadi korban perundungan siber yang parah. Ia kemudian menyewa jasa N, seorang peretas jenius yang eksentrik dan manipulatif, untuk melacak identitas anonim para perundung. Berdua, mereka menyelami sisi gelap dunia maya untuk membalas dendam dengan cara yang tak terbayangkan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Seporsi Mie Ayam Sebelum Mati",
			Author:          "Brian Khrisna",
			Publisher:       "Grasindo",
			Published:       time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.5,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/f21b3754-9e8b-441e-af2c-35f83e746f3a.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Drama", "Romance"},
			Language:        "Indonesian",
			TotalCopies:     4,
			AvailableCopies: 4,
			TotalPages:      216,
			Synopsis:        "Novel ini menghadirkan sebuah drama emosional yang lekat dengan realitas kehidupan sehari-hari, berpusat pada kenangan, penyesalan, dan momen-momen yang sering kali kita anggap remeh. Melalui simbolisme seporsi mie ayam yang dinikmati sebelum kematian tiba, Brian Khrisna menyajikan narasi menyentuh tentang bagaimana manusia menghadapi pahit manisnya takdir. Kisah ini mengajak pembaca untuk merefleksikan hubungan yang belum terselesaikan dan merangkul kedamaian sebelum waktu benar-benar habis di batas kehidupan.",
		},
		{
			ID:              uuid.New(),
			Title:           "Sisi Tergelap Surga",
			Author:          "Brian Khrisna",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.7,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/222331df-7c6a-44bb-bf76-31de58e713d0.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Drama"},
			Language:        "Indonesian",
			TotalCopies:     6,
			AvailableCopies: 6,
			TotalPages:      304,
			Synopsis:        "Mengambil latar di sudut-sudut kelam kota Jakarta yang seolah menjadi ironi bagi mereka yang menyebutnya 'surga', novel ini membongkar realitas kehidupan kaum marjinal dan masyarakat kelas pekerja bawah. Melalui karakter-karakternya yang hidup dengan latar belakang keluarga hancur dan impian yang kandas, Brian Khrisna menyuguhkan potret jujur tentang kemiskinan, kemunafikan sosial, serta perjuangan manusia untuk tetap waras. Buku ini adalah tamparan keras sekaligus pelukan hangat bagi siapa saja yang terus berjuang di tengah kejamnya ibu kota.",
		},
		{
			ID:              uuid.New(),
			Title:           "Bandung After Rain",
			Author:          "Wulan Nur Amalia",
			Publisher:       "Black Swan Books",
			Published:       time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.6,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/2c9560f2-13c7-4dc8-a3ed-bff4b91e8509.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Romance", "Drama"},
			Language:        "Indonesian",
			TotalCopies:     3,
			AvailableCopies: 3,
			TotalPages:      282,
			Synopsis:        "Hema dan Rania adalah dua jiwa yang dipertemukan dan diikat oleh kenangan-kenangan di bawah rintik hujan kota Bandung. Seiring dengan cuaca kota yang syahdu dan romantis, hubungan mereka diwarnai oleh konflik emosional, luka masa lalu, dan keraguan untuk melangkah maju. Novel ini menelusuri bagaimana mereka mencoba menyembuhkan satu sama lain, berhadapan dengan ekspektasi, serta mempertanyakan apakah cinta yang mereka bangun mampu bertahan melawan badai yang terus menguji kedewasaan mereka.",
		},
		{
			ID:              uuid.New(),
			Title:           "Teka-Teki Gambar Aneh",
			Author:          "Uketsu",
			Publisher:       "Gramedia Pustaka Utama",
			Published:       time.Date(2026, 2, 1, 0, 0, 0, 0, time.UTC),
			Ratings:         4.8,
			CoverURL:        "https://tccizyzzzjdrgutmsmuj.supabase.co/storage/v1/object/public/book-covers/covers/dd6e1bd3-783c-4bf5-8950-1ca7f9df6cfe.jpg",
			Category:        []string{"Novel"},
			Genre:           []string{"Mystery", "Thriller"},
			Language:        "Indonesian",
			TotalCopies:     8,
			AvailableCopies: 8,
			TotalPages:      312,
			Synopsis:        "Sebagai penerus dari fenomena Teka-Teki Rumah Aneh, Uketsu kembali hadir dengan misteri yang berpusat pada sembilan buah sketsa gambar yang sekilas tampak damai dan polos. Namun, ketika protagonis novel ini mulai menelisik dan menghubungkan detail-detail kecil dari gambar tersebut, kengerian demi kengerian mulai bermunculan. Sketsa-sketsa itu ternyata menyembunyikan jejak-jejak pembunuhan, rahasia keluarga yang busuk, dan kutukan masa lalu yang saling berkaitan. Pembaca akan diajak bermain teka-teki secara interaktif untuk merangkai sebuah kebenaran yang membuat bulu kuduk berdiri.",
		},
	}

	if err := db.Create(&books).Error; err != nil {
		log.Fatalf("Failed to seed books: %v", err)
	}

	log.Println("✅ Books seeded successfully")
}
